spring:
  flyway:
    baseline-on-migrate: true
  h2.console:
    enabled: true
    path: '/console'
  datasource :
    url: 'jdbc:h2:file:~/deaProjects\MonthlyExpensesApp\monthlyExpensesProd.db'
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              H2Dialect:

